#!/usr/bin/env bash
# Place-and-route fit sweep: how big a ternary GEMV block fits the Arty A7-35T?
# Synthesizes ternary_gemv_tiled across (K, NT, M) from toy to real BitNet FFN
# width and tabulates LUT/FF/DSP/BRAM/WNS so we can see where the design stops
# fitting and where register-resident storage must move to BRAM.
#
#   bash syn/fit_sweep.sh                      # default 100 MHz target
#   PERIOD=4.0 bash syn/fit_sweep.sh           # 250 MHz target
set -euo pipefail

PART="${PART:-xc7a35ticsg324-1L}"     # Arty A7-35T
PERIOD="${PERIOD:-10.0}"              # 100 MHz = the on-board sys clock
HERE="$(cd "$(dirname "$0")" && pwd)"
RTL="$(cd "$HERE/../rtl" && pwd)"
VSET="${VIVADO_SETTINGS:-/srv/fpga/Xilinx/2025.2/Vivado/settings64.sh}"
OUT="${OUT:-/tmp/ternfpga_fit}"
TCL="$HERE/fit_sweep.tcl"

# shellcheck disable=SC1090
source "$VSET"
mkdir -p "$OUT"; cd "$OUT"

# K=lanes/cycle  NT=tiles/row (KT=K*NT=row width)  M=output rows
POINTS=(
    "8 4 16"      # toy baseline — matches the cocotb sim (KT=32)
    "16 8 64"     # small real-ish (KT=128)
    "16 64 512"   # real width KT=1024 — register-resident x_reg/y_mem cost shows
    "32 32 512"   # wider lanes, KT=1024
    "32 64 512"   # KT=2048 — BitNet-2B-class FFN width
)

LUT_BUDGET=20800   # xc7a35t total

echo "# Ternary GEMV — Arty A7-35T Place-and-Route Fit Sweep"
echo
echo "Part \`$PART\`, OOC synthesis, target ${PERIOD} ns ($(awk "BEGIN{printf \"%.0f\", 1000/$PERIOD}") MHz). LUT budget = ${LUT_BUDGET}."
echo
echo "| K | NT | M | KT (width) | LUT | %LUT | FF | DSP | BRAM | WNS(ns) |"
echo "|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|"
for p in "${POINTS[@]}"; do
    read -r K NT M <<< "$p"
    log="fit_K${K}_NT${NT}_M${M}.log"
    if ! vivado -mode batch -nojournal -log "$log" -source "$TCL" \
            -tclargs "$PART" "$PERIOD" "$K" "$NT" "$M" \
            "$RTL/ternary_dot.sv" "$RTL/ternary_gemv_tiled.sv" >/dev/null 2>&1; then
        echo "| $K | $NT | $M | $((K*NT)) | **synth FAILED** (see $OUT/$log) | | | | | |"
        continue
    fi
    line=$(grep -m1 "^FITSTAT" "$log" || true)
    if [ -z "$line" ]; then
        echo "| $K | $NT | $M | $((K*NT)) | **no FITSTAT** (see $OUT/$log) | | | | | |"
        continue
    fi
    get() { echo "$line" | grep -oE "$1=[^ ]+" | head -1 | cut -d= -f2; }
    lut=$(get LUT); pct=$(awk "BEGIN{printf \"%.0f%%\", 100*$lut/$LUT_BUDGET}")
    echo "| $(get K) | $(get NT) | $(get M) | $(get KT) | $lut | $pct | $(get FF) | $(get DSP) | $(get BRAM) | $(get WNS) |"
done
echo
echo "_Generated by \`syn/fit_sweep.sh\`. Full per-point Vivado logs in \`$OUT/\`._"
