#!/usr/bin/env python3
"""Emit the ffn_glue_unit on-board test vector as a C header (gate/up/w + expected h_q + max|N|).

  python soc/firmware/gen_testvec_ffnglue.py > soc/firmware/testvec_ffnglue.h

Same synthetic case + bit-exact oracle as the cocotb test, at F=6912 (the real BitNet-2B intermediate
width) so the measured cycle count IS the per-layer number.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from ffn_glue_unit_ref import glue_unit_int, quantize_weight_fixed  # noqa: E402

F = 6912
rng = np.random.default_rng(7)
gate = rng.integers(-6000, 6000, F)
up = rng.integers(-6000, 6000, F)
norm_w = rng.standard_normal(F) * 0.1 + 1.0
w_q, _ = quantize_weight_fixed(norm_w, 16)
hq, amaxN, R, recip = glue_unit_int(gate, up, w_q)


def carr(name, flat, ctype):
    return f"static const {ctype} {name}[{len(flat)}] = {{{', '.join(str(int(v)) for v in flat)}}};"


print("// auto-generated by gen_testvec_ffnglue.py — ffn_glue_unit on-board test vector")
print(f"#define TV_F {F}")
print(f"#define TV_AMAX_LO {amaxN & 0xffffffff}u")
print(f"#define TV_AMAX_MID {(amaxN >> 32) & 0xffffffff}u")
print(f"#define TV_AMAX_HI {(amaxN >> 64) & 0xffffffff}u")
print(carr("FG_GATE", gate, "int"))
print(carr("FG_UP", up, "int"))
print(carr("FG_W", w_q, "short"))
print(carr("FG_HQ", hq, "signed char"))
