#!/usr/bin/env python3
"""Emit a fixed FFN-glue test vector as a C header, from the validated golden.

  python soc/firmware/gen_glue_testvec.py > soc/firmware/glue_testvec.h

The C glue (ffn_glue.h) must reproduce ffn_glue_ref.glue_hq bit-for-bit: same
integer N = relu(gate)^2*up*w and the same ties-to-even requant.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from ffn_glue_ref import glue_hq, quantize_weight_fixed  # noqa: E402

F = 200
rng = np.random.default_rng(11)
gate_int = rng.integers(-3000, 3000, size=F).astype(np.int64)
up_int = rng.integers(-3000, 3000, size=F).astype(np.int64)
norm_w_float = rng.uniform(0.5, 1.5, size=F)
qw, _ = quantize_weight_fixed(norm_w_float, bits=16)            # int16 fixed-point (integer-valued)
hq, _ = glue_hq(gate_int[None, :], up_int[None, :], qw)         # the golden h_q
hq = hq[0]

print("// auto-generated by gen_glue_testvec.py — FFN glue test vector (vs ffn_glue_ref)")
print(f"#define TV_F {F}")
print(f"static const int32_t GATE_INT[{F}] = {{{','.join(str(int(v)) for v in gate_int)}}};")
print(f"static const int32_t UP_INT[{F}] = {{{','.join(str(int(v)) for v in up_int)}}};")
print(f"static const double NORM_W[{F}] = {{{','.join(repr(float(v)) for v in qw)}}};")
print(f"static const signed char EXP_HQ[{F}] = {{{','.join(str(int(v)) for v in hq)}}};")
