#!/usr/bin/env python3
"""Emit an attention-glue test vector as a C header, from the validated golden.

  python soc/firmware/gen_attn_testvec.py > soc/firmware/attn_testvec.h

A small synthetic case (the glue is dimension-agnostic): the C glue (attn_glue.h) must
reproduce attn_ref's pre-o_proj attention vector (RoPE + GQA + causal softmax + sub_norm)
to float precision, run as per-token decode steps with a growing KV cache.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from attn_ref import attention  # noqa: E402
from ffn_ref import act_quant_int8  # noqa: E402

T, HID, NH, NKV, HD = 6, 64, 4, 2, 16        # hidden=NH*HD=64; kv=NKV*HD=32
THETA, EPS = 500000.0, 1e-5
rng = np.random.default_rng(29)


def tern(out, inp):
    return rng.choice([-1, 0, 1], size=(out, inp)).astype(np.int64)


x = rng.standard_normal((T, HID)) * 0.6
Wq, Wk, Wv, Wo = tern(HID, HID), tern(NKV * HD, HID), tern(NKV * HD, HID), tern(HID, HID)
sq, sk, sv, so = 1.21875, 1.79688, 2.29688, 0.96484
norm_w = rng.uniform(0.5, 1.5, size=HID)

y, inter = attention(x, Wq, sq, Wk, sk, Wv, sv, Wo, so, norm_w, NH, NKV, HD, THETA, EPS)
amax_x = act_quant_int8(x)[1].reshape(-1)            # per-token input absmax
exp_o = inter["attn_pre_oproj"]                       # (T, HID) post-sub_norm, pre o_proj


def carr(name, arr, ctype, fmt=str):
    flat = np.asarray(arr).reshape(-1)
    return f"static const {ctype} {name}[{flat.size}] = {{{','.join(fmt(v) for v in flat)}}};"


print("// auto-generated by gen_attn_testvec.py — attention glue test vector (vs attn_ref)")
print(f"#define TV_T {T}\n#define TV_HID {HID}\n#define TV_NH {NH}\n#define TV_NKV {NKV}")
print(f"#define TV_HD {HD}\n#define TV_MAXSEQ {T}")
print(f"#define TV_THETA {THETA!r}\n#define TV_EPS {EPS!r}")
print(f"#define TV_SQ {sq!r}\n#define TV_SK {sk!r}\n#define TV_SV {sv!r}\n#define TV_SO {so!r}")
print(carr("Q_INT", inter["q_int"], "int32_t", lambda v: str(int(v))))
print(carr("K_INT", inter["k_int"], "int32_t", lambda v: str(int(v))))
print(carr("V_INT", inter["v_int"], "int32_t", lambda v: str(int(v))))
print(carr("AMAX_X", amax_x, "double", lambda v: repr(float(v))))
print(carr("NORM_W", norm_w, "double", lambda v: repr(float(v))))
print(carr("EXP_O", exp_o, "float", lambda v: repr(float(v)) + "f"))
