#!/usr/bin/env python3
"""Emit the engine+ffn_glue cooperation test vector as a C header.

  python soc/firmware/gen_testvec_coresident.py > soc/firmware/testvec_coresident.h

A small FFN (hidden=K*NT=64, INTER=M=32): the engine computes the gate/up ternary GEMVs, their
int32 outputs feed the ffn_glue unit (relu^2*up*w + int8 requant). Reuses the engine packing
(ternary_ref) + the glue oracle (ffn_glue_unit_ref) so the on-board result is bit-exact end-to-end.
"""
import os
import random
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from ternary_ref import pack_activations, pack_weights, ternary_gemv_golden  # noqa: E402
from ffn_glue_unit_ref import glue_unit_int, quantize_weight_fixed          # noqa: E402

K, NT, M = 8, 8, 32          # hidden = K*NT = 64, INTER = M = 32
KT = K * NT
rng = random.Random(2025)
x = [rng.randint(-30, 30) for _ in range(KT)]
Wg = [[rng.choice([-1, 0, 1]) for _ in range(KT)] for _ in range(M)]
Wu = [[rng.choice([-1, 0, 1]) for _ in range(KT)] for _ in range(M)]
gate = ternary_gemv_golden(Wg, x)
up = ternary_gemv_golden(Wu, x)

nrng = np.random.default_rng(5)
norm_w = nrng.standard_normal(M) * 0.1 + 1.0
w_q, _ = quantize_weight_fixed(norm_w, 16)
hq, amaxN, R, recip = glue_unit_int(np.array(gate), np.array(up), w_q)

X = [pack_activations(x[t * K:(t + 1) * K]) for t in range(NT)]
WGT = [pack_weights(Wg[m][t * K:(t + 1) * K]) for m in range(M) for t in range(NT)]
WUT = [pack_weights(Wu[m][t * K:(t + 1) * K]) for m in range(M) for t in range(NT)]

print("// auto-generated by gen_testvec_coresident.py — engine+ffn_glue cooperation test vector")
print(f"#define TV_K {K}\n#define TV_NT {NT}\n#define TV_M {M}")
print(f"#define TV_AMAX_LO {amaxN & 0xffffffff}u")
print(f"#define TV_AMAX_MID {(amaxN >> 32) & 0xffffffff}u")
print(f"#define TV_AMAX_HI {(amaxN >> 64) & 0xffffffff}u")
print(f"static const unsigned long long X[{NT}] = {{{', '.join(f'0x{v:016x}ULL' for v in X)}}};")
print(f"static const unsigned short WGT[{len(WGT)}] = {{{', '.join(str(v) for v in WGT)}}};")
print(f"static const unsigned short WUT[{len(WUT)}] = {{{', '.join(str(v) for v in WUT)}}};")
print(f"static const short WQ[{M}] = {{{', '.join(str(int(v)) for v in w_q)}}};")
print(f"static const signed char EXP_HQ[{M}] = {{{', '.join(str(int(v)) for v in hq)}}};")
print(f"static const int EXP_GATE[{M}] = {{{', '.join(str(int(v)) for v in gate)}}};")
