#!/usr/bin/env python3
"""Emit a fixed GEMV test vector as a C header for the on-board firmware.

  python soc/firmware/gen_testvec.py > soc/firmware/testvec.h

Uses the same NumPy golden + base-3 packing as the RTL tests, so the on-board
result is checked against the identical reference.
"""
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from ternary_ref import ternary_gemv_golden  # noqa: E402
from export_weights import pack_row_trits5    # noqa: E402

K, M = 8, 16
rng = random.Random(1234)
x = [rng.randint(-30, 30) for _ in range(K)]
W = [[rng.choice([-1, 0, 1]) for _ in range(K)] for _ in range(M)]

xu = sum((x[i] & 0xFF) << (8 * i) for i in range(K))     # x_flat as one uint64 (lane 0 = LSB)
wb = b"".join(pack_row_trits5(W[m]) for m in range(M))   # M rows x BPR bytes, in stream order
exp = ternary_gemv_golden(W, x)

print("// auto-generated by gen_testvec.py — fixed GEMV test vector (K=8, M=16)")
print(f"// x = {x}")
print(f"#define TV_K {K}")
print(f"#define TV_M {M}")
print(f"static const unsigned long long X = 0x{xu:016x}ULL;")
print(f"static const unsigned char WB[{len(wb)}] = {{{', '.join(str(b) for b in wb)}}};")
print(f"static const int EXP[{M}] = {{{', '.join(str(v) for v in exp)}}};")
