#!/usr/bin/env python3
"""Emit the attention-unit on-board test vector as a C header (q/KV/LUT + expected num+sum).

  python soc/firmware/gen_testvec_attn.py > soc/firmware/testvec_attn.h

Same synthetic case + bit-exact oracle as the cocotb test, at T=64 (the peripheral's T_MAX).
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from attn_unit_ref import attn_unit_int, exp_lut, EXP_LSB  # noqa: E402

D, T = 128, 64
rng = np.random.default_rng(23)
q = rng.standard_normal(D) * 0.5
K = rng.standard_normal((T, D)) * 0.5
V = rng.standard_normal((T, D)) * 0.5
qs, ks, vs = (np.abs(a).max() / 32767.0 for a in (q, K, V))
q_i = np.round(q / qs).astype(np.int64)
K_i = np.round(K / ks).astype(np.int64)
V_i = np.round(V / vs).astype(np.int64)
score_shift = int(round(np.log2(EXP_LSB * np.sqrt(D) / (qs * ks))))
EL = exp_lut()
_, _, _, s_exp, num_exp = attn_unit_int(q_i, K_i, V_i, score_shift, EL)


def carr(name, flat, ctype, fmt=str):
    return f"static const {ctype} {name}[{len(flat)}] = {{{', '.join(fmt(int(v)) for v in flat)}}};"


print("// auto-generated by gen_testvec_attn.py — attention-unit on-board test vector")
print(f"#define TV_D {D}\n#define TV_T {T}\n#define TV_SHIFT {score_shift}\n#define TV_EXPN {len(EL)}")
print(f"#define TV_SUM {int(s_exp)}u")
print(carr("ATV_Q", q_i, "short", lambda v: str(v)))
print(carr("ATV_K", K_i.reshape(-1), "short", lambda v: str(v)))
print(carr("ATV_V", V_i.reshape(-1), "short", lambda v: str(v)))
print(carr("ATV_ELUT", EL, "unsigned short", lambda v: str(v)))
print(carr("ATV_NUM", num_exp, "long long", lambda v: str(v) + "LL"))
