#!/usr/bin/env python3
"""Emit a fixed streaming-GEMV test vector as a C header for the on-board firmware.

  python soc/firmware/gen_testvec_gemv.py > soc/firmware/testvec_gemv.h

Uses the same NumPy golden + packing as the RTL tests (ternary_ref), so the on-board
result is checked against the identical reference. K=8 so each activation tile word
is a clean uint64; weight tiles are 2-bit-code uint16, streamed row-major.
"""
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "models"))
from ternary_ref import pack_activations, pack_weights, ternary_gemv_golden  # noqa: E402

K, NT, M = 8, 4, 16          # KT = K*NT = 32 output width; M output rows
KT = K * NT
rng = random.Random(2025)
x = [rng.randint(-30, 30) for _ in range(KT)]
W = [[rng.choice([-1, 0, 1]) for _ in range(KT)] for _ in range(M)]

X = [pack_activations(x[t * K:(t + 1) * K]) for t in range(NT)]                # NT uint64 words
WT = [pack_weights(W[m][t * K:(t + 1) * K]) for m in range(M) for t in range(NT)]  # M*NT uint16
exp = ternary_gemv_golden(W, x)

print("// auto-generated by gen_testvec_gemv.py — streaming GEMV on-board test vector")
print(f"// x = {x}")
print(f"#define TV_K {K}")
print(f"#define TV_NT {NT}")
print(f"#define TV_M {M}")
print(f"static const unsigned long long X[{NT}] = {{{', '.join(f'0x{v:016x}ULL' for v in X)}}};")
print(f"static const unsigned short WT[{len(WT)}] = {{{', '.join(str(v) for v in WT)}}};")
print(f"static const int EXP[{M}] = {{{', '.join(str(v) for v in exp)}}};")
