#!/usr/bin/env python3
"""Emit the glue's transcendental LUTs as a C header (static ROM, no libm).

  python soc/firmware/gen_glue_luts.py > soc/firmware/glue_luts.h

RoPE cos/sin as Q15 int16 (pos x head_dim/2), and softmax exp(-i*LSB) as Q15 int16. These
replace cos/sin/exp on-device so the glue firmware is PURE INTEGER (no soft-float, no libm) —
as lean as main_dmabw, which ran fine on-board (the soft-float firmware trapped).
"""
import numpy as np

HEAD_DIM, MAXPOS, THETA = 128, 130, 500000.0
EXP_N, EXP_LSB, Q = 4096, 0.01, 15

inv = 1.0 / (THETA ** (np.arange(0, HEAD_DIM, 2, dtype=np.float64) / HEAD_DIM))
ang = np.outer(np.arange(MAXPOS), inv)
cos_q = np.clip(np.round(np.cos(ang) * (1 << Q)), -32768, 32767).astype(np.int64).ravel()
sin_q = np.clip(np.round(np.sin(ang) * (1 << Q)), -32768, 32767).astype(np.int64).ravel()
exp_q = np.clip(np.round(np.exp(-np.arange(EXP_N) * EXP_LSB) * (1 << Q)), 0, 32767).astype(np.int64)


def arr(name, a):
    return f"static const short {name}[{a.size}] = {{{','.join(str(int(v)) for v in a)}}};"


print("// auto-generated by gen_glue_luts.py — RoPE + softmax LUTs (Q15), no libm")
print(f"#define LUT_HEAD_DIM {HEAD_DIM}")
print(f"#define LUT_MAXPOS {MAXPOS}")
print(f"#define LUT_HALF {HEAD_DIM // 2}")
print(f"#define LUT_Q {Q}")
print(f"#define EXP_N {EXP_N}")
print(f"#define EXP_LSB_INV {int(round(1.0 / EXP_LSB))}   // logit-drop -> index: idx = drop_q15 * 100 >> 15")
print(arr("ROPE_COS", cos_q))   # [MAXPOS*HALF], row pos -> [pos*HALF + i]
print(arr("ROPE_SIN", sin_q))
print(arr("EXP_LUT", exp_q))    # [EXP_N], exp(-idx*LSB) in Q15
